export const diagnosis_to_specializations = {
                "col": ["GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "flu": ["GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "respiratory infection": ["GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "bronchitis": ["PULMONOLOGIST", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "pneumonia": ["PULMONOLOGIST", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "asthma": ["PULMONOLOGIST", "ALLERGY CLINIC", "IMMUNOLOGIST & ALLERGIST"],
                "sinusitis": ["OTOLARYNGOLOGIST", "ALLERGY CLINIC", "IMMUNOLOGIST & ALLERGIST"],
                "allergic rhinitis": ["ALLERGY CLINIC", "IMMUNOLOGIST & ALLERGIST", "OTOLARYNGOLOGIST"],
                "conjunctivitis": ["OPHTHALMOLOGIST"],
                "ear infection": ["OTOLARYNGOLOGIST", "pediatrics"],
                "sleep apnea": ["PULMONOLOGIST", "OTOLARYNGOLOGIST"],
                "general phisician": ["GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "cardiologist": ["CARDIOLOGIST"],
                "gastrologist": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST"],
                "orthopedic surgeon": ["ORTHOPAEDIC SURGEON", "ORTHOPED"],
                "orthopedic & spinal surgery": ["ORTHOPEDIC & SPINAL SURGERY"],
                "rheumatologist": ["RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST"],
                "neurologist": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST"],
                "dermatologist": ["DERMATOLOGIST"],
                "urologist": ["UROLOGIST"],
                "endocrinologist": ["ENDOCRINOLOGIST"],
                "obstetrics and gynaecologist": ["OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS"],
                "psychiatrist": ["PSYCHIATRIST", "NEURO PSYCHIATRIST"],
                "dentist": ["DENTIST", "DENTAL & MAXILOFACIAL SURGERY", "DENTAL SURGEON"],
                "ophthalmologist": ["OPHTHALMOLOGIST"],
                "pediatrician": ["pediatrics", "FAMILY MEDICINE"],
                "pulmonologist": ["PULMONOLOGIST"],
                "nutritionist": ["NUTRITIONIST"],
                "hematologist": ["HEMATOLOGY", "HEMATOLOGIST"],
                "infectious disease": ["CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "general surgeon": ["GENERAL SURGEON", "GENERAL SURGEON & LAPAROSCOPY"],
                "urologistist": ["UROLOGIST", "NEPHROLOGIST"],
                "podiatry": ["podiatry"],
                "pain medicine": ["pain medicine"],
                "rehabilitation specialist": ["REHABILITATION SPECIALIST"],
                "allergy and immunology": ["allergy and immunology", "IMMUNOLOGIST & ALLERGIST"],
                "hepatology": ["hepatology"],
                "gastroenterology": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST"],

                "hypertension": ["CARDIOLOGIST",  "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "high blood pressure": ["CARDIOLOGIST",  "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "high cholesterol": ["CARDIOLOGIST", "ENDOCRINOLOGIST"],
                "angina": ["CARDIOLOGIST"],
                "heart palpitations": ["CARDIOLOGIST", " ELECTROPHYSIOLOGIST"],
                "diabetes": ["ENDOCRINOLOGIST",  "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "type 1 diabetes": ["ENDOCRINOLOGIST"],
                "type 2 diabetes": ["ENDOCRINOLOGIST"],
                "hypothyroidism": ["ENDOCRINOLOGIST",  "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "hyperthyroidism": ["ENDOCRINOLOGIST",  "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "obesity": ["ENDOCRINOLOGIST", "NUTRITIONIST"],

                "acid reflux": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST"],
                "gastroesophageal reflux": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST"],
                "abdominal pain": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST", "GENERAL SURGEON", "GENERAL SURGEON & LAPAROSCOPY"],
                "gastric ulcer": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST"],
                "constipation": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST",  "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "diarrhea": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST", "CONSULTANT INFECTIOUS DISEASE", "INFECTIOUS DISEASE"],
                "hemorrhoids": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST", "GENERAL SURGEON", "GENERAL SURGEON & LAPAROSCOPY"],
                "irritable bowel syndrome": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST"],
                "liver disease": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST", "hepatology"],
                "jaundice": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST", "hepatology"],

                // # Musculoskeletal & Pain
                "back pain": ["ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY", "REHABILITATION SPECIALIST"],
                "neck pain": ["ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY", "REHABILITATION SPECIALIST"],
                "joint pain": ["RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST", "ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY"],
                "arthritis": ["RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST", "ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY"],
                "tendonitis": ["ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY", "RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST"],
                "carpal tunnel": ["ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY", "NEUROLOGIST", "PAEDIATRIC NEUROLOGIST"],
                "fibromyalgia": ["RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST", "pain medicine"],
                "sprain": ["ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY", "REHABILITATION SPECIALIST"],

                // # Neurology & Headaches
                "migraine": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST"],
                "headache": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "tension headache": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST"],
                "cluster headache": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST"],
                "dizziness": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST", "OTOLARYNGOLOGIST"],
                "vertigo": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST", "OTOLARYNGOLOGIST"],
                "neuropathy": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST", "ENDOCRINOLOGIST"],
                "seizures": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST",],

                // # Dermatology & Allergy
                "eczema": ["DERMATOLOGIST"],
                "dermatitis": ["DERMATOLOGIST"],
                "acne": ["DERMATOLOGIST"],
                "psoriasis": ["DERMATOLOGIST", "RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST"],
                "skin rash": ["DERMATOLOGIST", "allergy and immunology"],
                "hives": ["DERMATOLOGIST", "allergy and immunology"],
                "fungal infection": ["DERMATOLOGIST", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "cellulitis": ["DERMATOLOGIST", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "alopecia": ["DERMATOLOGIST"],
                "alopecia areata": ["DERMATOLOGIST", "RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST"],

                // # Urology & Nephrology
                "urinary tract infection": ["UROLOGIST", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "kidney stones": ["UROLOGIST", "NEPHROLOGIST"],
                "incontinence": ["UROLOGIST", "OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS",],
                "prostate issues": ["UROLOGIST"],
                "kidney disease": ["NEPHROLOGIST",  "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],

                // # Reproductive & Endocrine
                "menstrual pain": ["OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS",],
                "irregular periods": ["OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS", "ENDOCRINOLOGIST"],
                "infertility": ["OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS", "ENDOCRINOLOGIST"],
                "pcos": ["OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS", "ENDOCRINOLOGIST"],
                "menopause symptoms": ["OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS", "ENDOCRINOLOGIST"],
                "erectile dysfunction": ["UROLOGIST", "ENDOCRINOLOGIST"],

                // # Mental Health
                "depression": ["PSYCHIATRIST", "NEURO PSYCHIATRIST", "PAEDIATRIC PSYCHOLOGIST", "CHILD PSYCHOLOGIST", "CLINICAL PSYCHOLOGIST", "PSYCHOLOGIST"],
                "anxiety": ["PSYCHIATRIST", "NEURO PSYCHIATRIST", "PAEDIATRIC PSYCHOLOGIST", "CHILD PSYCHOLOGIST", "CLINICAL PSYCHOLOGIST", "PSYCHOLOGIST"],
                "stress": ["PSYCHIATRIST", "NEURO PSYCHIATRIST", "PAEDIATRIC PSYCHOLOGIST", "CHILD PSYCHOLOGIST", "CLINICAL PSYCHOLOGIST", "PSYCHOLOGIST"],
                "insomnia": ["PSYCHIATRIST", "NEURO PSYCHIATRIST", "NEUROLOGIST", "PAEDIATRIC NEUROLOGIST"],
                "adhd": ["PSYCHIATRIST", "NEURO PSYCHIATRIST", "NEUROLOGIST", "PAEDIATRIC NEUROLOGIST"],
                "ocd": ["PSYCHIATRIST", "NEURO PSYCHIATRIST"],
                "ptsd": ["PSYCHIATRIST", "NEURO PSYCHIATRIST"],

                // # Pediatrics & Vaccines
                "vaccination": ["pediatrics", "FAMILY MEDICINE"],
                "growth concern": ["pediatrics", "ENDOCRINOLOGIST"],
                "developmental delay": ["pediatrics", "NEUROLOGIST", "PAEDIATRIC NEUROLOGIST",],
                "ear pain": ["OTOLARYNGOLOGIST", "pediatrics"],
                "thrush": ["pediatrics", "CONSULTANT INFECTIOUS DISEASE", "INFECTIOUS DISEASES"],

                // # Preventive & Wellness
                "annual physical": [ "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "health checkup": [ "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "travel vaccine": ["FAMILY MEDICINE", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "smoking cessation": ["PULMONOLOGIST", "FAMILY MEDICINE"],

                // # Miscellaneous
                "fatigue": [ "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH", "ENDOCRINOLOGIST"],
                "weight gain": ["ENDOCRINOLOGIST", "NUTRITIONIST"],
                "weight loss": ["ENDOCRINOLOGIST", "GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST",],
                "fever": ["CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "snoring": ["OTOLARYNGOLOGIST", "PULMONOLOGIST"],
                "swollen lymph nodes": ["CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES", "HEMATOLOGY", "HEMATOLOGIST",],
                "appendicitis": ["GENERAL SURGEON", "GENERAL SURGEON & LAPAROSCOPY"],
                "gallstones": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST", "GENERAL SURGEON", "GENERAL SURGEON & LAPAROSCOPY"],
                "pancreatitis": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST",],
                "hepatitis": ["hepatology", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "covid-19": ["CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES", "PULMONOLOGIST"],
                "rheumatoid arthritis": ["RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST"],
                "lupus": ["RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST"],
                "bipolar disorder": ["PSYCHIATRIST", "NEURO PSYCHIATRIST"],
                "schizophrenia": ["PSYCHIATRIST", "NEURO PSYCHIATRIST"],
                "anemia": ["HEMATOLOGY", "HEMATOLOGIST", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "testicular pain": ["UROLOGISTIST"],
                "breast lump": ["OBSTETRICS AND GYNAECOLOGIST", "GYNAECOLOGIST", "GYNAECOLOGY & OBSTETRICS", "MEDICAL ONCOLOGIST", "ONCOLOGIST", "PEDIATRIC ONCOLOGIST"],
                "urinary retention": ["UROLOGIST", "NEPHROLOGIST"],
                "gout": ["RHEUMATOLOGY", "RHEUMATOLOGY / MEDICINE (JOINTS SPECIALIST)", "RHEUMATOLOGIST"],
                "eye infection": ["OPHTHALMOLOGIST"],
                "pink eye": ["OPHTHALMOLOGIST"],
                "tonsillitis": ["OTOLARYNGOLOGIST"],
                "dental abscess": ["DENTIST", "DENTAL & MAXILOFACIAL SURGERY", "DENTAL SURGEON"],
                "cough": ["PULMONOLOGIST", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "sore throat": ["OTOLARYNGOLOGIST", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "loss of taste or smell": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST", "CONSULTANT INFECTIOUS DISEASE", "CONSULTANT INFECTIOUS DISEASES", "INFECTIOUS DISEASES"],
                "eczema flare-up": ["DERMATOLOGIST"],
                "warts": ["DERMATOLOGIST"],
                "urine odor": ["UROLOGIST"],
                "itching": ["DERMATOLOGIST", "allergy and immunology", "IMMUNOLOGIST & ALLERGIST", "ALLERGY CLINIC"],
                "nausea": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "vomiting": ["GASTROENTEROLOGY", "GASTROENTEROLOGIST", "PAEDIATRIC GASTROENTEROLOGIST", "GENERAL PHYSICIAN", "MEDICINE", "FAMILY MEDICINE", "FAMILY MEDICINE & COMMUNITY HEALTH"],
                "panic attack": ["PSYCHIATRIST", "NEURO PSYCHIATRIST", "PAEDIATRIC PSYCHOLOGIST", "CHILD PSYCHOLOGIST", "CLINICAL PSYCHOLOGIST", "PSYCHOLOGIST"],
                "social anxiety": ["PSYCHIATRIST", "NEURO PSYCHIATRIST", "PAEDIATRIC PSYCHOLOGIST", "CHILD PSYCHOLOGIST", "CLINICAL PSYCHOLOGIST", "PSYCHOLOGIST"],
                "memory loss": ["NEUROLOGIST", "PAEDIATRIC NEUROLOGIST", "PSYCHIATRIST", "NEURO PSYCHIATRIST"],
                "foot pain": ["ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY", "podiatry"],
                "heel pain": ["ORTHOPAEDIC SURGEON", "ORTHOPEDIC & SPINAL SURGERY", "podiatry"]
        }